language: ruby
bundler_args: --without release doc
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
notifications:
  email:
    - blambeau@gmail.com
